#!/usr/bin/env bash
# Nginx web server and set configurations

sudo apt-get update
sudo apt-get install -y nginx

#Ownership config
sudo chown -R "$USER:$USER" /var/www/

#Write to index file
echo "Hello World!" > /var/www/html/index.html

#Restart nginx
sudo service nginx restart
