#!/usr/bin/env bash
# Nginx web server and set configurations

sudo apt-get update
sudo apt-get install -y nginx

#Ownership config
sudo chown -R "$USER:$USER" /var/www/

#Write to index file
echo "Hello World!" > /var/www/html/index.html

#Redirection
site="https://www.youtube.com/watch?v=QH2-TGUlwu4"
new="server_name _;\n\trewrite ^/redirect_me/$ $site permanent;"

sudo sed -i "s/server_name\ _;/$new/" /etc/nginx/sites-available/default

#Restart nginx
sudo service nginx restart
