#!/usr/bin/env bash
# Nginx web server and set configurations

sudo apt-get update
sudo apt-get install -y nginx

#Ownership config
sudo chown -R "$USER:$USER" /var/www/

#Write to index file
echo "Hello World!" > /var/www/html/index.html

#Redirection
new="localhost;\n\tlocation \/redirect_me {\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}"
sed -i "s/localhost;/$new/" /etc/nginx/sites-available/default

#Restart nginx
sudo service nginx restart
