#!/usr/bin/env bash
# Displays "Best School" ten times

i=0;
while ((i < 10))
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	
	else
		echo "Best School"
	fi;
	i=$((i+1));
done
