#!/usr/bin/env bash
# Run nginx as nginx

pkill apache2
chmod 644 /etc/nginx/nginx.conf

chown -R nginx /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
su - nginx -c nginx
